gesdinet_jwt_refresh_token:
    refresh_token_class: App\Entity\RefreshToken
    ttl: 2592000
    ttl_update: true
    single_use: true
    token_parameter_name: REFRESH_TOKEN
    cookie:
        enabled: true
        same_site: strict
        http_only: true
        secure: false
        path: /api/token/refresh
