nelmio_cors:
    defaults:
        allow_credentials: true
        origin_regex: true
        allow_origin: ['http://localhost:3000', 'https://pral-calc.divineion.fr']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
        '^/api/':
            allow_origin: ['http://localhost:3000', 'https://pral-calc.divineion.fr']
            allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
            allow_headers: [ 'Content-Type', 'Authorization' ]
